Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using E_Players_AspNETCore.Interfaces;

namespace E_Players_AspNETCore.Models
{
    public class Equipe : EPlayersBase , IEquipe
    {
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }

        private const string PATH = "Database/equipe.csv";
        /// <summary>
        /// Método construtor para gerar a pasta.
        /// </summary>
        public Equipe(){
            CreateFolderAndFile(PATH);
        }
        /// <summary>
        /// Método para adicionar a linha no arquivo "csv".
        /// </summary>
        /// <param name="e">Equipe</param>
        /// <returns>Linha no arquivo "csv".</returns>
        private string PrepararLinha(Equipe e){
            return $"{e.IdEquipe};{e.Nome};{e.Imagem}";
        }
        /// <summary>
        /// Cadastra a equipe no arquivo "csv".
        /// </summary>
        /// <param name="e">Equipe</param>
        public void Create(Equipe e){
            string[] linha = {PrepararLinha(e)};
            File.AppendAllLines(PATH, linha);
        }
        /// <summary>
        /// Deleta uma equipe do arquivo "csv".
        /// </summary>
        /// <param name="idEquipe"></param>
        public void Delete(int id){
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(';')[0] == id.ToString());
            RewriteCSV(PATH, linhas);
        }
        /// <summary>
        /// Lê todas as linhas do arquivo "csv".
        /// </summary>
        /// <returns>Conteúdo do arquivo "csv".</returns>
        public List<Equipe> ReadAll(){
            List<Equipe> equipes = new List<Equipe>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Equipe equipe = new Equipe();
                equipe.IdEquipe = Int32.Parse(linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add(equipe);
            }
            return equipes;
        }
        /// <summary>
        /// Altera um atributo do objeto.
        /// </summary>
        /// <param name="e">Equipe</param>
        public void Update(Equipe e){
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(';')[0] == IdEquipe.ToString());
            linhas.Add(PrepararLinha(e));
            RewriteCSV(PATH, linhas);
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using E_Players_AspNETCore.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace E_Players_AspNETCore.Controllers
{
    public class EquipeController : Controller
    {
        Equipe equipeModel = new Equipe();
        public IActionResult Index(){
            ViewBag.Equipes = equipeModel.ReadAll();
            return View();
        }
        public IActionResult Cadastrar(IFormCollection form){
            Equipe novaEquipe   = new Equipe();
            novaEquipe.IdEquipe = Int32.Parse(form["IdEquipe"]);
            novaEquipe.Nome     = form["Nome"];
            
            var file = form.Files[0];
            var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

            if (file != null){
                if (!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream(path, FileMode.Create)){
                    file.CopyTo(stream);
                }
                novaEquipe.Imagem = file.FileName;
            }else{
                novaEquipe.Imagem = "padrao.png";
            }

            equipeModel.Create(novaEquipe);
            ViewBag.Equipes = equipeModel.ReadAll();

            return LocalRedirect("~/Equipe");
        }

        [Route("Equipe/{id}")]
        public IActionResult Excluir(int id){
            equipeModel.Delete(id);
            return LocalRedirect("~/Equipe");
        }
    }
}

Views/Equipe/Index.cshtml
@model Equipe
@{
    ViewData["Title"] = "Equipes";
}

<div class="titulo_pagina">
    <h1>cadastro de @ViewData["Title"]</h1>
</div>

<form class="cadastro" action="@Url.Action("Cadastrar")" method="post" enctype="multipart/form-data">

    <div class="campo">
        <label for="IdEquipe">ID</label>
        <input type="text" name="IdEquipe" id="IdEquipe">
    </div>    

    <div class="campo">
        <label for="Nome">Nome</label>
        <input type="text" name="Nome" id="Nome">
    </div>

    <div class="campo">
        <label for="Imagem">Imagem</label>
        <input type="file" name="Imagem" id="Imagem">
    </div>

    
    <button type="submit" class="gradient btn">Cadastrar</button>

</form>

<table class="table table-responsive table-striped container">
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th>Imagem</th>
        <th>Ações</th>
    </thead>
    
    <tbody>
        @foreach (Equipe item in ViewBag.Equipes){
            <tr>
                <td>@item.IdEquipe</td>
                <td>@item.Nome</td>
                <td><img src="img/Equipes/@item.Imagem" alt="Imagem da Equipe @item.Nome"></td>
                <td>
                    <a class="fas fa-trash" asp-area="" asp-controller="Equipe" asp-action="Excluir" asp-route-id="@item.IdEquipe"></a>
                </td>
            </tr>
        }
    </tbody>
</table>